local _
local AddonName, ns =...
local L = CreateFrame"Frame"
ns.L = L

if (GetLocale() == "zhCN") then 
	--默认语言为简体中文

elseif (GetLocale() == "ruRU") then 
	--by:ZamestoTV
	L.resd	= "Перезагрузите интерфейс, чтобы восстановить настройки по умолчанию"
	L.confirm	= "Подтвердить"
	L.cancel	= "Отмена"
	L.dtools2	= "Украшение интерфейса"
	L.captext	= "|cff00EE00Shift|r - удерживайте для перемещения стандартных аватаров и т.д.\n(Настройка панели действий может отключить панель действий)\n|cff00EE00/di|r - Быстро открыть интерфейс настроек\n|cff00EE00/npd|r - Восстановить настройки индикаторов здоровья по умолчанию"
	L.printh2	= "|cff00EE00/rl|r - Перезагрузить интерфейс\n|cff00EE00/di|r - Быстро открыть интерфейс настроек"
	L.printh	= "Инструкции"

	L.acu1	= "Панель действий"
	L.acu2	= "Улучшение и украшение панели действий"
	L.acc1	= "Черная рамка"
	L.acc2	= "Окрасить рамку кнопок панели действий"
	L.acp1	= "Продвинутое украшение"
	L.acp2	= "Украсить фон рамки кнопок панели действий"
	L.acr1	= "Скрыть аним. иконок"
	L.acr2	= "Отключить анимацию заклинаний для новых иконок в 10.0"
	L.unu1	= "Окна"
	L.unu2	= "Улучшение и украшение стандартных окон"
	L.unft1 = "Текстура Элиты"
	L.unft2 = "Окно игрока с текстурой золотого дракона"
	L.una1 	= "Окна игрока"
	L.una2	= "Окно для постепенного исчезновения аватара без цели в бою"
	L.pnc1	= "Переименование персонажа"
	L.pnc2	= "|cff00FF00/gn/name|r - Изменить имя локального персонажа"
	L.unfn1 = "Скрыть имя"
	L.unfn2 = "Скрыть имя игрока"
	L.unc1	= "Цвет класса"
	L.unc2	= "Использовать яркий набор цветов для классов"
	L.otb1	= "Отслеживание"
	L.otb2	= "Украшение текста отслеживания заданий (Возможны сбои в поведении интерфейса во время боя)"
	L.sfu1	= "Шрифты"
	L.sfu2	= "Украшение большей части текста в игре"
	L.ruu1	= "Окна рейда"
	L.ruu2	= "Украшение окон рейда"
	L.npu1	= "Индикатор здоровья"
	L.npu2	= "Простое улучшение и украшение индикаторов здоровья"
	L.tiu1	= "Подсказки"
	L.tiu2	= "Украшение и улучшение подсказок при наведении мыши"

	L.aur1	= "Авторемонт"
	L.aur2	= "Автоматический ремонт снаряжения (приоритет у ремонта гильдии)"
	L.aus1	= "Автопродажа"
	L.aus2	= "Автоматическая продажа серого мусора"
	L.aua1	= "Автоскриншоты"
	L.aua2	= "Автоматическое создание скриншотов при получении достижений"
	L.aug1	= "Автоформирование"
	L.aug2	= "Автоматическое формирование шифротекста (|cffFFFF00/1|r)"
	L.fsl1	= "Быстрый сбор"
	L.fsl2	= "Ускорение окна сбора"
	L.ist1	= "Прерывание закл."
	L.ist2	= "Подсказка о прерывании заклинания цели"
	L.vap1	= "Голосовые объявления"
	L.vap2	= "Голосовая подсказка при получении метки"
	L.bfm1	= "Перемещение панелей"
	L.bfm2	= "Свободное перемещение встроенных панелей"
	L.ifs1	= "Информация о данных"
	L.ifs2	= "Скорость передвижения, FPS, Задержка, Память"
	L.ifsb1	= "Большой шрифт"
	L.ifsb2	= "Увеличение размера шрифта для информации о данных"
	L.cfp1	= "Улучшение чата"
	L.cfp2	= "Украшение и улучшение чата"
	L.cfbb1	= "Нижняя кнопка"
	L.cfbb2	= "Перемещение кнопки чата в нижнюю часть окна"
	L.cbi1	= "Индикатор боя"
	L.cbi2	= "Индикатор боя от Bigfoot"

	L.oufd1	= "Диабло"
	L.oufd2	= "Окно игрока Сферы Диабло от oUF"
	L.oufcc1= "Цвет класса"
	L.oufcc2= "Окрашивание сферы в цвет класса"
	L.dpet1	= "Окно питомца"
	L.dpet2	= "Окно питомца над сферой жизни"
	L.dduf1	= "Стандартное окно"
	L.dduf2	= "Включить стандартное окно игрока, скрытый oUF"
	L.uisl1	= "Блок масштаба UI"
	L.uisl2	= "Открыть и заблокировать масштаб интерфейса (После настройки масштаба интерфейса необходимо сбросить позиции)"
	L.daml1	= "Тонкая настройка"
	L.daml2	= "Настройка и блокировка некоторых панелей действий (Режим редактирования может вызывать ошибки во время боя)"

	L.tipc1	= "Подсказка: Следовать"
	L.tipc2	= "Подсказка: Не следовать"
	L.tipc3	= "Подсказка: Следовать вне боя"
	L.sqw1	= "Задержка закл."
	L.sqw2	= "Задержка последовательности заклинаний"
	L.brtx	= "Версия"
	L.adrl	= "Перезагрузить"
	L.liver	= "Прямая трансляция"
	L.slb		= "Рекомендация"
	L.resdef	= "По умолчанию"
	L.respos	= "Сбросить"
	L.liveroom	= "|cffEEFF7FDouyuLive:|r427397"
	L.print	= "Открыть интерфейс настроек"

	-- Чат
	L.say		= "С"
	L.yell		= "К"
	L.party		= "Г"
	L.guild		= "Г"
	L.raid		= "Р"
	L.instance		= "П"
	L.general1		= "О"
	L.general2		= "Общий"
	L.general3		= "У вас нет общего канала"
	L.trade1		= "Т"
	L.trade2		= "Торговля"
	L.trade3		= "Вы не в торговом канале, присоединитесь в главном городе"
	L.lookingforgroup1		= "Л"
	L.lookingforgroup2		= "Поиск группы"
	L.lookingforgroup3		= "Присоединился к поиску группы"
	L.lookingforgroup4		= "Покинул поиск группы"
	L.world1		= "М"
	L.world2		= "Мир"
	L.world3		= "Присоединился к мировому каналу"
	L.world4		= "Покинул мировой канал"
	L.rep		= "Р"
	L.eql		= "Ур. экипировки"
	L.class		= "Класс"
	L.spec		= "Специализация"

	-- Информация
	L.fps 	= "FPS"
	L.lag 	= "Задержка"
	L.player 	= "И"
	L.target 	= "Ц"
	L.vehicle 	= "Т"
	L.none 	= "Нет"
	L.lootspec 	= "СПЕЦ"
	L.str 	= "Сил"
	L.agi 	= "Лов"
	L.int 	= "Инт"
	L.cri 	= "Крит"
	L.has 	= "Есть"
	L.mas 	= "Мастер"
	L.ver 	= "Вер"
	L.clearm	= "Очистить память"
	L.total		= "Всего"
	L.totalb	= "Всего, включая Blizzard"
	L.sspec		= "Сменить специализацию"
	L.nospec	= "Еще не специализирован"
	L.slspec	= "Сменить специализацию для сбора"

	-- Модули
	L.guildrepair	= "В этот раз использован ремонт гильдии"
	L.guildra		= "Осталось доступных ремонтов гильдии"
	L.selfrepair	= "Ремонт за свой счет"
	L.norepair		= "У меня нет денег на ремонт снаряжения."
	L.sellg			= "Продажа мусора"
	L.hidoroff		= "Сторона невидима или персонаж не в сети, невозможно пригласить"
	L.cutin 		= "Вырезать "
	L.enytc 		= "Введите имя, которое хотите изменить, оставьте пустым для восстановления оригинального имени"
	L.carti 		= "Подтвердите и перезагрузите интерфейс"

	-- Другое
	L.buyco		= "Успешно куплен 1 предмет"
	L.buydpc	= "Ошибка покупки, изменилась цена"
	L.buyalp	= "Купить по минимальной цене"
	L.untre		= "Невозможно сбросить"
	L.hbre		= "Сброшено"
	L.hbre		= "Сброшено"
	L.ltteam	= "Покидание команды"
	L.ftayt		= "Для этого мероприятия ваша команда заполнена и будет удалена из списка"
	L.era		= "ЭРА"

	-- Настройки аддона
	L.cdscr	= "Настройки DBM, Skada.. изменены, перезагрузка интерфейса для применения изменений!"
	L.confirm 	="Подтвердить"
	L.cancel 	="Отмена"
	L.setup	= "Настройка"
	L.ritss	= "Сбросить интерфейс для сохранения настроек"

	-- Настройки CVar
	L.comlc = "Отключить настройки во время боя"
	L.decpt = "Обнаружен плагин сбора ошибок, отключение стандартного отображения ошибок LUA"
	L.nedtc = "Ошибок не обнаружено. Плагин сбора включает стандартное отображение ошибок LUA"
	L.on 	="ВКЛ"
	L.off 	="ВЫКЛ"
	L.tgcb 	= "Полоса заклинаний цели"
	L.comif = "Информация о бое"
	L.teaml = "Расположение команды"
	L.tprl 	= "Расположение рейда на 20 человек"
	L.tfprl = "Расположение рейда на 25 человек"
	L.fprl 	= "Расположение рейда на 40 человек"
	L.tips	= "Подсказки"
	L.itine = "Если есть ошибка, перезагрузите интерфейс!"
	L.reload 	="Перезагрузить интерфейс?"
	L.confirm 	="Подтвердить"
	L.cancel 	="Отмена"
	L.uhset 	= "Настройки привычек использования"
	L.care 		="Осторожно!"
	L.comlc ="Полоса заклинаний цели"
	L.comlc ="Исходная информация о бое"

	-- Подсказки
	L.afk	= "АФК"
	L.offl	= "Не в сети"
	L.rare	= "Редкий"
	L.raree	= "Редкий элитный"
	L.elite	= "Элитный"
	L.ghost	= "Призрак"
	L.dead	= "Мертв"
	L.targ= "Цель"
	L.you	= "ВЫ"
	L.epicra	= "Эпический рейтинг"
	L.dungeons	= "Подземелья"
	L.ratle	= "Уровни рейтинга"
	L.item	= "Предмет"
	L.spell	= "Заклинание"

else
	
	L.resd	= "Reload interface to restore default"
	L.confirm	= "Confirm"
	L.cancel	= "Cancel"
	L.dtools2	= "UI beautify"
	L.captext	= "|cff00EE00Shift|r down to move default avatars, dark blood cells, data information, etc\n(Adjusting the action bar can turn off the action bar)\n|cff00EE00/di|r Quickly open the settings interface\n|cff00EE00/npd|r Restore nameplates default settings"
	L.printh2	= "|cff00EE00/rl|r Reload interface\n|cff00EE00/di|r Quickly open the settings interface"
	L.printh	= "Instructions"

	L.acu1	= "ActionBar"
	L.acu2	= "Action bar enhance and beautify"
	L.acc1	= "Blackout border"
	L.acc2	= "Dye action bar button border"
	L.acp1	= "Advanced beautify"
	L.acp2	= "Beautify the background of the action bar button border"
	L.acr1	= "Hide icon animation"
	L.acr2	= "Close the newly added icon casting animation in 10.0"
	L.unu1	= "Frame enhance"
	L.unu2	= "Default unitframe beautify enhance"
	L.unft1 = "Elite texture"
	L.unft2 = "Player frame made of golden dragon texture"
	L.una1 	= "PlayerFrame fadeout"
	L.una2	= "A framework for gradually disappearing avatars without a target in battle"
	L.pnc1	= "Character renaming"
	L.pnc2	= "|cff00FF00/gn/name|r Change local player character names"
	L.unfn1 = "Hide name"
	L.unfn2 = "Hide player name"
	L.unc1	= "Class color adjustment"
	L.unc2	= "Use a bright set of professional colors"
	L.otb1	= "Tracking beautify"
	L.otb2	= "Task tracking text beautification(Possible interface behavior failure during combat)"
	L.sfu1	= "Font beautify"
	L.sfu2	= "Beautify most of the text in the game"
	L.ruu1	= "RaidFrame beautify"
	L.ruu2	= "RaidFrame beautify"
	L.npu1	= "Nameplate enhance"
	L.npu2	= "Simple Nameplate beautify enhance"
	L.tiu1	= "Tip enhance"
	L.tiu2	= "Mouse tip beautify and enhance"

	L.aur1	= "Auto repair"
	L.aur2	= "Auto repair equipment (priority given to guild repairs)"
	L.aus1	= "Auto sales"
	L.aus2	= "Autoally sell gray garbage"
	L.aua1	= "Auto screenshot"
	L.aua2	= "Obtain Auto screenshots of achievements"
	L.aug1	= "Auto formation"
	L.aug2	= "Auto formation of ciphertext(|cffFFFF00/1|r)"
	L.fsl1	= "Quick Pick"
	L.fsl2	= "Pick frame acceleration"
	L.ist1	= "Interrupt prompt"
	L.ist2	= "Interrupt target casting prompt"
	L.vap1	= "Voice Announcements"
	L.vap2	= "Mark gain voice prompt"
	L.bfm1	= "Panel movement"
	L.bfm2	= "Free movement of builtin panel frame"
	L.ifs1	= "Data information"
	L.ifs2	= "Movement speed, FPS, Lag, Memory"
	L.ifsb1	= "Large font"
	L.ifsb2	= "Increase the font size of data information"
	L.cfp1	= "Chat enhance"
	L.cfp2	= "Talk about beautify and enhance"
	L.cfbb1	= "Bottom button"
	L.cfbb2	= "Move the chat bar button to the bottom of the frame"
	L.cbi1	= "CombatIndicator"
	L.cbi2	= "CombatIndicator by Bigfoot"

	L.oufd1	= "Diablo Orb"
	L.oufd2	= "Diablo Orb PlayerFrame by oUF"
	L.oufcc1= "Class color"
	L.oufcc2= "Orb dyeing of class color"
	L.dpet1	= "Pet frame"
	L.dpet2	= "Pet frame above the orb of life"
	L.dduf1	= "Default Frame"
	L.dduf2	= "Enable default playerFrame hidden by oUF"
	L.uisl1	= "UI Scale lock"
	L.uisl2	= "Open and lock UI scale(After adjusting the UI scale, it is necessary to reset the position)"
	L.daml1	= "Actionfine-tuning"
	L.daml2	= "Customize and lock some action bars(Editing mode will report errors during combat)"

	L.tipc1	= "Tip: Follow"
	L.tipc2	= "Tip: Do not follow"
	L.tipc3	= "Tip: Non Combat Follow"
	L.sqw1	= "Cast delay"
	L.sqw2	= "Cast sequence delay"
	L.brtx	= "Version"
	L.adrl	= "Reload"
	L.liver	= "LiveRoom"
	L.slb		= "Recommendation"
	L.resdef	= "Restore default"
	L.respos	= "Reset position"
	L.liveroom	= "|cffEEFF7FDouyuLive:|r427397"
	L.print	= "Open the settings interface"


	--chat
	L.say		= "S"
	L.yell		= "Y"
	L.party		= "P"
	L.guild		= "G"
	L.raid		= "R"
	L.instance		= "I"
	L.general1		= "G"
	L.general2		= "General"
	L.general3		= "You don't have a general channel"
	L.trade1		= "T"
	L.trade2		= "Trade"
	L.trade3		= "You are not on the trading channel, please join in the main city"
	L.lookingforgroup1		= "L"
	L.lookingforgroup2		= "LookingForGroup"
	L.lookingforgroup3		= "Joined LookingForGroup"
	L.lookingforgroup4		= "Leaving LookingForGroup"
	L.world1		= "W"
	L.world2		= "world"
	L.world3		= "Joined World Channel"
	L.world4		= "Leaving World Channel"
	L.rep		= "R"
	L.eql		= "Eq level"
	L.class		= "Class"
	L.spec		= "Spec"


	--info
	L.fps 	= "FPS"
	L.lag 	= "Lag"
	L.player 	= "P"
	L.target 	= "T"
	L.vehicle 	= "V"
	L.none 	= "Nil"
	L.lootspec 	= "SPEC"
	L.str 	= "Str"
	L.agi 	= "Agi"
	L.int 	= "Int"
	L.cri 	= "Cri"
	L.has 	= "Has"
	L.mas 	= "Mas"
	L.ver 	= "Ver"
	L.clearm	= "Clean up memory"
	L.total		= "Total"
	L.totalb	= "Total incl.Blizzard"
	L.sspec		= "Switch Spec"
	L.nospec	= "Not specialized yet"
	L.slspec	= "Switch Pick Spec"


	--modules
	L.guildrepair	= "This time using guild repair"
	L.guildra		= "Remaining guild repairs available"
	L.selfrepair	= "Self funded repair"
	L.norepair		= "I don't have money to repair equipment."
	L.sellg			= "Selling garbage"
	L.hidoroff		= "The other party is invisible or has no character online, unable to invite"
	L.cutin 		= "Cut "
	L.enytc 		= "Enter the name you want to change, do not enter to restore the original name"
	L.carti 		= "Confirm and reload the interface"
	
	
	--other
	L.buyco		= "Successfully purchased 1 item"
	L.buydpc	= "Purchase failure, price change"
	L.buyalp	= "Buy one at the lowest price"
	L.untre		= "Unable to reset"
	L.hbre		= "Has been reset"
	L.hbre		= "Has been reset"
	L.ltteam	= "Leaving the team"
	L.ftayt		= "For this activity, your team is full and will be removed from the list"
	L.era		= "ERA"
	
	
	--setaddon
	L.cdscr	= "DBM, Skada.. Settings have been changed, reloading interface application changes!"
	L.confirm 	="Confirm"
	L.cancel 	="Cancel"
	L.setup	= "Set up"
	L.ritss	= "Reset interface to save settings"


	--setcvar
	L.comlc = "Disable settings during battles"
	L.decpt = "Detected error collection plugin turning off default LUA error display"
	L.nedtc = "No error detected. The collection plugin opens the default LUA error display"
	L.on 	="ON"
	L.off 	="OFF"
	L.tgcb 	= "Target casting bar"
	L.comif = "Combat information"
	L.teaml = "Team Layout"
	L.tprl 	= "20 person raid layout"
	L.tfprl = "25 person raid layout"
	L.fprl 	= "40 person raid layout"
	L.tips	= "Tips" 
	L.itine = "If there is an error, please reload the interface!"
	L.reload 	="Reload UI?"
	L.confirm 	="Confirm"
	L.cancel 	="Cancel"
	L.uhset 	= "Usage habits settings"
	L.care 		="Careful!"
	L.comlc ="Target casting bar"
	L.comlc ="Original Combat information"


	--tooltip
	L.afk	= "AFK"
	L.offl	= "Offline"
	L.rare	= "Rare"
	L.raree	= "Rareelite"
	L.elite	= "Elite"
	L.ghost	= "Ghost"
	L.dead	= "Dead"
	L.targ= "Target"
	L.you	= "YOU"
	L.epicra	= "Epic Rating"
	L.dungeons	= "Dungeons"
	L.ratle	= "Rating Levels"
	L.item	= "Item"
	L.spell	= "Spell"
	
end
